all: ex1 ex2 ex3 ex4

ex1: 
	$(CC) "Exercício 1.c" -o ex1.exe
ex2: 
	$(CC) "Exercício 2.c" -o ex2.exe
ex3: 
	$(CC) "Exercício 3.c" -lm -o ex3.exe
# o -lm é nessesário pois usa o math.h
ex4: 
	$(CC) "Exercício 4.c" -lm -o ex4.exe
