all: ex1 ex2 ex3 ex4 ex5 ex6 ex7

ex1:
	$(CC) "Exercício 1.c" -o ex1.exe
ex2:
	$(CC) "Exercício 2.c" -o ex2.exe
ex3:
	$(CC) "Exercício 3.c" -o ex3.exe
ex4:
	$(CC) "Exercício 4.c" -o ex4.exe
ex5:
	$(CC) "Exercício 5.c" -o ex5.exe
ex6:
	$(CC) "Exercício 6.c" -o ex6.exe
ex7:
	$(CC) "Exercício 7.c" -o ex7.exe
